name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: huyunoki
          filename: github-metrics.svg

          base: header, activity, community, repositories
          config_timezone: Asia/Tokyo

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 5

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          plugin_followup: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_lines: yes

          template: classic
