name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }] # 毎日更新
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: huyunoki
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          config_display: large

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 5

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_followup: yes

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_lines: yes

          config_theme: gotham
